name: Check jobs
on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
    secrets:
      S3_ACCESS_KEY:
        required: false
      S3_SECRET_NAME:
        required: false
      YA_YT_TOKEN:
        required: false


jobs:
  integration-test:
    name: Integration tests
    uses: ./.github/workflows/integration-tests.yaml
    with:
      runs-on-value: ${{ inputs.runs-on-value }}
    secrets:
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_NAME: ${{ secrets.S3_SECRET_NAME }}
      YA_YT_TOKEN: ${{ secrets.YA_YT_TOKEN }}
