name: Check jobs
on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
    secrets:
      S3_CONFIG:
        required: false

jobs:
  integration-test:
    name: Integration tests
    uses: ./.github/workflows/integration-tests.yaml
    with:
      runs-on-value: ${{ needs.start-vm.outputs.label }}
    secrets:
      S3_CONFIG: ${{ secrets.S3_CONFIG }}
