name: Check jobs
on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
      s3-config:
        required: false
        type: string

jobs:
  check:
    runs-on: ${{ inputs.runs-on-value }}
    steps:
      - name: Integration tests
        uses: ./.github/workflows/integration-tests.yaml
        with:
          runs-on-value: ${{ needs.start-vm.outputs.label }}
          s3-config: ${{ inputs.s3-config }}
